# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A simple blog by Mitch
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! This is where I document my projects. As a beginner 
  I know it can be frustrating to get your projects to work. Here I'll write 
  down the challenges I came across and how I solved them. Via this blog 
  I hope I'll be able to help out my fellow struggling enthusiasts by 
  describing how I solved my challenges. Good luck to you all and remember, 
  if everything fails use: 'sudo !!'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mvbakker.nl" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
